name: Castle Client - Deploy

on:
  workflow_run:
    workflows: ["Castle Client - Build & Test"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      skip_build_test:
        description: 'Skip build and test (use latest successful run)'
        required: false
        default: false
        type: boolean

jobs:
  build-and-test:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.skip_build_test != 'true'
    uses: ./.github/workflows/castle-client-build-test.yml

  deploy-development:
    if: always() && ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch' && (needs.build-and-test.result == 'success' || needs.build-and-test.result == 'skipped') && (github.event.inputs.environment == 'development' || github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production')))
    needs: [build-and-test]
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install published Entente packages in castle-client
        working-directory: examples/castle-client
        run: pnpm add @entente/types@^0.1.2 @entente/consumer@^0.1.2 @entente/fixtures@^0.1.2

      - name: Install castle-client dependencies
        working-directory: examples/castle-client
        run: pnpm install

      - name: Install Entente CLI globally
        run: npm install -g @entente/cli@latest

      - name: Build castle-client
        env:
          ENTENTE_SERVICE_URL: ${{ vars.ENTENTE_SERVICE_URL }}
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: pnpm --filter @entente/example-castle-client build

      - name: Check deployment readiness
        env:
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: |
          cd examples/castle-client
          VERSION=$(node -p "require('./package.json').version")
          entente can-i-deploy \
            --type consumer \
            --service castle-client \
            --service-version $VERSION \
            --environment development

      - name: Deploy to Cloudflare Workers (Development)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: examples/castle-client
          command: deploy --name castle-client-dev --env development
        env:
          ENVIRONMENT: development

      - name: Record deployment
        env:
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: |
          cd examples/castle-client
          VERSION=$(node -p "require('./package.json').version")
          entente deploy-service \
            --name castle-client \
            --service-version $VERSION \
            --environment development \
            --type consumer

      - name: Run smoke tests
        run: |
          sleep 10
          curl -f https://castle-client-dev.${{ vars.CLOUDFLARE_WORKERS_SUBDOMAIN }}.workers.dev/health || exit 1

  deploy-staging:
    if: always() && ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch' && (needs.build-and-test.result == 'success' || needs.build-and-test.result == 'skipped') && (github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'))) && needs.deploy-development.result == 'success'
    needs: [build-and-test, deploy-development]
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install published Entente packages in castle-client
        working-directory: examples/castle-client
        run: pnpm add @entente/types@^0.1.2 @entente/consumer@^0.1.2 @entente/fixtures@^0.1.2

      - name: Install castle-client dependencies
        working-directory: examples/castle-client
        run: pnpm install

      - name: Install Entente CLI globally
        run: npm install -g @entente/cli@latest

      - name: Build castle-client
        env:
          ENTENTE_SERVICE_URL: ${{ vars.ENTENTE_SERVICE_URL }}
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: pnpm --filter @entente/example-castle-client build

      - name: Check deployment readiness
        env:
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: |
          cd examples/castle-client
          VERSION=$(node -p "require('./package.json').version")
          entente can-i-deploy \
            --type consumer \
            --service castle-client \
            --service-version $VERSION \
            --environment staging

      - name: Deploy to Cloudflare Workers (Staging)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: examples/castle-client
          command: deploy --name castle-client-staging --env staging
        env:
          ENVIRONMENT: staging

      - name: Record deployment
        env:
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: |
          cd examples/castle-client
          VERSION=$(node -p "require('./package.json').version")
          entente deploy-service \
            --name castle-client \
            --service-version $VERSION \
            --environment staging \
            --type consumer

      - name: Run smoke tests
        run: |
          sleep 10
          curl -f https://castle-client-staging.${{ vars.CLOUDFLARE_WORKERS_SUBDOMAIN }}.workers.dev/health || exit 1

  deploy-production:
    if: always() && ((github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch' && (needs.build-and-test.result == 'success' || needs.build-and-test.result == 'skipped') && github.event.inputs.environment == 'production')) && needs.deploy-staging.result == 'success'
    needs: [build-and-test, deploy-staging]
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install published Entente packages in castle-client
        working-directory: examples/castle-client
        run: pnpm add @entente/types@^0.1.2 @entente/consumer@^0.1.2 @entente/fixtures@^0.1.2

      - name: Install castle-client dependencies
        working-directory: examples/castle-client
        run: pnpm install

      - name: Install Entente CLI globally
        run: npm install -g @entente/cli@latest

      - name: Build castle-client
        env:
          ENTENTE_SERVICE_URL: ${{ vars.ENTENTE_SERVICE_URL }}
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: pnpm --filter @entente/example-castle-client build

      - name: Check deployment readiness
        env:
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: |
          cd examples/castle-client
          VERSION=$(node -p "require('./package.json').version")
          entente can-i-deploy \
            --type consumer \
            --service castle-client \
            --service-version $VERSION \
            --environment production

      - name: Deploy to Cloudflare Workers (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: examples/castle-client
          command: deploy --name castle-client --env production
        env:
          ENVIRONMENT: production

      - name: Record deployment
        env:
          ENTENTE_API_KEY: ${{ secrets.ENTENTE_API_KEY }}
        run: |
          cd examples/castle-client
          VERSION=$(node -p "require('./package.json').version")
          entente deploy-service \
            --name castle-client \
            --service-version $VERSION \
            --environment production \
            --type consumer

      - name: Run smoke tests
        run: |
          sleep 10
          curl -f https://castle-client.${{ vars.CLOUDFLARE_WORKERS_SUBDOMAIN }}.workers.dev/health || exit 1
